# 语言设置
language: zh_CN

# 飞行费用设置
fly-cost:
  minute: 10.0    # 每分钟的价格
  hour: 100.0     # 每小时的价格
  day: 1000.0     # 每天的价格
  week: 5000.0    # 每周的价格
  month: 15000.0  # 每月的价格

# 时间限制设置
time-limits:
  minute:
    min: 5
    max: 60
  hour:
    min: 1
    max: 24
  day:
    min: 1
    max: 7
  week:
    min: 1
    max: 4
  month:
    min: 1
    max: 12

# 提示设置
notifications:
  bossbar:
    enabled: true
    # 提前多少秒显示BossBar (0 = 一直显示)
    show-before: 15
    # 支持的颜色: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
    colors:
      normal: GREEN
      warning: RED
    # 支持的样式: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
    style: SEGMENTED_20
    # 是否显示进度条
    show-progress: true
  chat:
    enabled: true
    # 聊天框提醒间隔（秒）
    reminder-interval: 5
    # 开始提醒的时间（秒）
    warning-time: 15

# 存储设置
storage:
  # 存储类型: JSON, SQLITE, MYSQL
  type: JSON
  
  # JSON 存储设置 (仅在 type: JSON 时使用)
  json:
    # 自动保存间隔（秒）
    save-interval: 30
    # 是否启用备份
    enable-backup: true
    # 最大备份文件数量
    max-backups: 5
  
  # MySQL 设置 (仅在 type: MYSQL 时使用)
  mysql:
    host: localhost
    port: 3306
    database: minecraft
    username: root
    password: password
    table: paytofly_data
    # 连接池设置
    pool:
      max-connections: 5
      connection-timeout: 30000
      max-retries: 3

  # SQLite 设置 (仅在 type: SQLITE 时使用)
  sqlite:
    file: database.db

# 缓存设置
cache:
  # 是否启用缓存
  enabled: true
  # 缓存最大容量
  max-size: 1000
  # 缓存生存时间（分钟）
  ttl-minutes: 30
  # 清理间隔（分钟）
  cleanup-interval-minutes: 5
  # 是否在启动时预加载数据
  preload-on-init: true
  # 写入模式：true=写穿透，false=写回
  write-through: true

# bStats 设置
metrics:
  enabled: true  # 是否启用数据统计

# 更新检查设置
update-checker:
  enabled: true    # 是否启用更新检查
  debug: false     # 是否显示详细错误信息

# 时间计算方式
time-calculation:
  # 可选: REAL_TIME (现实时间) 或 PLAY_TIME (游戏时间)
  mode: "REAL_TIME"

settings:
  # 默认飞行状态
  default-fly: false
  # 管理员加入提示更新
  admin-update-notice: true
  # 是否启用无限飞行权限
  infinite-flight: true
  # 是否在禁飞世界中禁用无限飞行权限
  disable-infinite-in-restricted: true
  creative:
    allow-flight: true    # 是否允许创造模式玩家飞行
    bypass-permission: "paytofly.creative.bypass"  # 绕过创造模式飞行限制的权限

worlds:
  # 这些世界不需要购买就能飞行
  free-fly:
    - "creative"
    - "lobby"
  # 这些世界禁止飞行（即使购买了也不能飞）
  disabled:
    - "pvp"
    - "minigames"
  # 是否在进入禁飞世界时发送提示
  notify-on-enter: true

# 飞行特效设置
flight-effects:
  # 是否启用飞行特效系统
  enabled: true
  # 特效配置
  effects:
    # 粒子密度 (1-10, 数值越高粒子越多)
    particle-density: 5
    # 特效范围（块为单位）
    effect-range: 30
    # 是否在玩家静止时减少特效
    reduce-when-idle: true
  # 音效设置
  sounds:
    # 是否启用音效
    enabled: true
    # 音效音量 (0.0-1.0)
    volume: 0.7
    # 音效音调 (0.1-2.0)
    pitch: 1.0
  # 特效购买价格设置
  purchase:
    # 是否启用特效购买系统
    enabled: true
    # 各特效的价格（永久购买）
    prices:
      basic: 100.0      # 基础特效
      rainbow: 500.0    # 彩虹特效
      star: 800.0       # 星星特效
      fire: 1200.0      # 火焰特效
      magic: 2000.0     # 魔法特效
      dragon: 5000.0    # 龙息特效
  # 时间购买设置
  time-purchase:
    # 是否启用按时间购买特效
    enabled: true
    # 时间购买价格倍数（基于永久价格）
    hour-multiplier: 0.1    # 每小时价格倍数
    day-multiplier: 2.0     # 每天价格倍数
    week-multiplier: 12.0   # 每周价格倍数

# 飞行速度控制设置
flight-speed:
  # 是否启用飞行速度控制
  enabled: true
  # 默认飞行速度等级
  default-speed: "normal"
  # 最大允许速度 (0.1-1.0)
  max-speed: 1.0
  # 速度过渡设置
  transition:
    # 是否启用平滑过渡
    smooth: true
    # 过渡时间（毫秒）
    duration: 250
  # 自动调整设置
  auto-adjust:
    # 是否启用自动速度调整
    enabled: false
    # 基于剩余时间的速度调整
    time-based: true
  # 速度购买价格设置
  purchase:
    # 是否启用速度购买系统
    enabled: true
    # 各速度等级的价格（永久购买）
    prices:
      slow: 50.0        # 缓慢速度
      normal: 0.0       # 普通速度（免费）
      fast: 200.0       # 快速
      very_fast: 600.0  # 极速
      super_fast: 1500.0 # 超速
      light_speed: 3000.0 # 光速
      warp_speed: 8000.0  # 曲速
  # 时间购买设置
  time-purchase:
    # 是否启用按时间购买速度
    enabled: true
    # 时间购买价格倍数（基于永久价格）
    hour-multiplier: 0.1    # 每小时价格倍数
    day-multiplier: 2.0     # 每天价格倍数
    week-multiplier: 12.0   # 每周价格倍数

# MHDF-Tools 兼容设置
mhdf-tools:
  # 是否启用和MHDF-Tools的飞行权限同步
  sync-flight: true
  # 是否静默执行同步命令，不在控制台显示MHDF-Tools消息
  silent-sync: true
  # 是否在玩家切换世界时同步飞行权限
  sync-on-world-change: true
  # 是否在玩家重生时同步飞行权限
  sync-on-respawn: true