name: Build PayToFly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PayToFly
        path: target/PayToFly-*.jar

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: PayToFly
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: PayToFly-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 